version: "3.8"
services:
  frontend:
    container_name: comspacity_frontend_container
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/code
    ports:
      - 8501:8501
    depends_on:
      - backend
  backend:
    container_name: comspacity_backend_container
    build: ./backend
    restart: always
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
